# Generated by Django 6.0.1 on 2026-02-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0011_alter_cihaz_isim_alter_duyuru_icerik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profil",
            name="email_dogrulama_tarihi",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Email Doğrulama Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="profil",
            name="email_dogrulandi",
            field=models.BooleanField(
                default=False, verbose_name="Email Doğrulandı mı?"
            ),
        ),
        migrations.AddField(
            model_name="profil",
            name="status",
            field=models.CharField(
                choices=[
                    ("pasif_ogrenci", "Pasif Öğrenci (Email Doğrulı)"),
                    ("aktif_ogrenci", "Aktif Öğrenci (Admin Onaylı)"),
                    ("iptal", "İptal Edildi"),
                ],
                default="pasif_ogrenci",
                max_length=20,
                verbose_name="Öğrenci Durumu",
            ),
        ),
    ]
