# Generated by Django 5.2.11 on 2026-02-13 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0012_profil_email_dogrulama_tarihi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profil",
            name="kod_olusturma_tarihi",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cihaz",
            name="lab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rezervasyon.laboratuvar",
                verbose_name="Bağlı Olduğu Laboratuvar",
            ),
        ),
        migrations.AlterField(
            model_name="randevu",
            name="durum",
            field=models.CharField(
                choices=[
                    ("onay_bekleniyor", "Onay Bekleniyor"),
                    ("onaylandi", "Onaylandı"),
                    ("reddedildi", "Reddedildi"),
                    ("geldi", "Geldi"),
                    ("gelmedi", "Gelmedi"),
                    ("iptal_edildi", "İptal Edildi"),
                ],
                default="onay_bekleniyor",
                max_length=20,
                verbose_name="Rezervasyon Durumu",
            ),
        ),
    ]
