# Generated by Django 5.2.11 on 2026-04-07 22:58

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("rezervasyon", "0013_profil_kod_olusturma_tarihi_alter_cihaz_lab_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AktifOgrenciler",
        ),
        migrations.CreateModel(
            name="AktifKullanicilar",
            fields=[],
            options={
                "verbose_name": "Aktif Kullanıcı",
                "verbose_name_plural": "🟢 Aktif Kullanıcılar",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="profil",
            name="status",
            field=models.CharField(
                choices=[
                    ("pasif_kullanici", "Pasif kullanıcı (Email Doğrulı)"),
                    ("aktif_kullanici", "Aktif Kullanıcı (Admin Onaylı)"),
                    ("iptal", "İptal Edildi"),
                ],
                default="pasif_kullanici",
                max_length=20,
                verbose_name="Kullanıcı Durumu",
            ),
        ),
    ]
