# Generated by Django 5.2.11 on 2026-05-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0014_delete_aktifogrenciler_aktifkullanicilar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='okul_numarasi',
        ),
    ]
