# Generated by Django 5.2.11 on 2026-05-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0015_remove_profil_okul_numarasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='duyurular/', verbose_name='Görsel / Reklam Afişi'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='kapatilabilir_mi',
            field=models.BooleanField(default=True, help_text='İşaretliyse kullanıcılar çarpıya basıp bir daha görmeyebilir.', verbose_name='Kapatılabilir mi?'),
        ),
    ]
