# Generated by Django 5.2.11 on 2026-06-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0016_duyuru_gorsel_duyuru_kapatilabilir_mi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="randevu",
            name="durum",
            field=models.CharField(
                choices=[
                    ("onay_bekleniyor", "Onay Bekleniyor"),
                    ("onaylandi", "Onaylandı"),
                    ("reddedildi", "Reddedildi"),
                    ("geldi", "Geldi"),
                    ("gelmedi", "Gelmedi"),
                    ("iptal_edildi", "İptal Edildi"),
                ],
                default="onaylandi",
                max_length=20,
                verbose_name="Rezervasyon Durumu",
            ),
        ),
    ]
